//
//  Know Your Customer UITestsLaunchTests.swift
//  Know Your Customer UITests
//
//  Created by Matt Novoselov on 18/07/25.
//

import XCTest

final class KYCUITestsLaunchTests: XCTestCase {
    // Basic launch test generated by Xcode.

    // swiftlint:disable:next static_over_final_class
    override class var runsForEachTargetApplicationUIConfiguration: Bool {
        true
    }

    override func setUpWithError() throws {
        continueAfterFailure = false
    }

    @MainActor
    func testLaunch() throws {
        let app = XCUIApplication()
        app.launch()

        // Insert steps here to perform after app launch but before taking a screenshot,
        // such as logging into a test account or navigating somewhere in the app

        let attachment = XCTAttachment(screenshot: app.screenshot())
        attachment.name = "Launch Screen"
        attachment.lifetime = .keepAlways
        add(attachment)
    }
}
